<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_StateProvince_stateProvince</name>
   <tag></tag>
   <elementGuidId>561c706c-aaf6-4cea-8125-dedaf1581d10</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#stateProvince</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='stateProvince']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>97500a66-6092-485f-866c-637726a60ebe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>fff69424-876a-4d16-bfe5-2467b574b00e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>stateProvince</value>
      <webElementGuid>48f86ed1-3890-40c3-a371-87f4e1038b9b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>stateProvince</value>
      <webElementGuid>994f7db8-29c0-46f3-b03e-dbc46b1496a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>10</value>
      <webElementGuid>3682d3d9-1e48-4885-919b-9522a12b98c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>focused</value>
      <webElementGuid>cae7e0d7-e0ff-4fe3-86c3-a94d5e4fcfa7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;stateProvince&quot;)</value>
      <webElementGuid>0188c4e1-4cf2-4aaf-89e2-e408534ca68a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='stateProvince']</value>
      <webElementGuid>542dff67-06fe-4dcf-99af-68a6b6ccecc6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//fieldset[@id='null']/p[7]/input</value>
      <webElementGuid>d3ae95c5-da40-4fd8-acae-bb72b32ce69b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p[7]/input</value>
      <webElementGuid>7baf2507-01d1-4fba-8222-f6392f885a09</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'stateProvince' and @name = 'stateProvince']</value>
      <webElementGuid>2c784284-7cfb-462a-83ab-4628f3c6b388</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
