<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_concat(What, , s the patient phone nu_a898f7</name>
   <tag></tag>
   <elementGuidId>781455a9-a693-4ff8-af3d-24291b7244bb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#fr954-field</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='fr954-field']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>06de2037-9d00-46d7-953b-1831375852ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>9de4391e-b804-4bbc-a334-0edd470e2e0c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>fr954-field</value>
      <webElementGuid>4e0b8413-9052-4d72-8057-b9a784705121</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>phoneNumber</value>
      <webElementGuid>31f7b9c6-c65c-4211-8302-0a40057a5501</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>phone focused</value>
      <webElementGuid>e2f77b68-cd50-4e1c-930c-127fb74de715</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;fr954-field&quot;)</value>
      <webElementGuid>5fb16321-13f7-4ef7-a6a1-1b38b4101fec</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='fr954-field']</value>
      <webElementGuid>d87f571b-386e-4452-9e14-93ce6b9b9ce6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//fieldset[@id='phoneNumberLabel']/p/input</value>
      <webElementGuid>1b17924b-110f-48d4-a120-823d0f7de8aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//fieldset[2]/p/input</value>
      <webElementGuid>d89b1e8b-fe3a-4383-a52d-046b535b6af5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'fr954-field' and @name = 'phoneNumber']</value>
      <webElementGuid>01461e2e-8bbf-42cc-ad84-beb42e02a189</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
