<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Who is the patient related to_person-_c8514e</name>
   <tag></tag>
   <elementGuidId>b431654a-f8d5-4214-b253-f77966b326d2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input.person-typeahead.ng-pristine.ng-untouched.ng-valid.ng-empty</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@type='text'])[15]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c0b0476e-c0ed-4bda-a8a7-d2702759579a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>d566222a-de9a-42b1-9a6c-f980317489bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>person-typeahead ng-pristine ng-untouched ng-valid ng-empty</value>
      <webElementGuid>7bfc3a20-a24f-4cd6-a25c-6b851ccedc44</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Person Name</value>
      <webElementGuid>c5d9ff8f-5464-4849-aa4d-1b248bd16396</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-model</name>
      <type>Main</type>
      <value>relationship.name</value>
      <webElementGuid>fc1774a0-4756-4348-8656-b92df1fac70c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>typeahead</name>
      <type>Main</type>
      <value>person as person.display for person in getPersons($viewValue) | limitTo:5</value>
      <webElementGuid>15083686-19f7-4c3f-8c50-640e3dd1661d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>typeahead-min-length</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>95deb8de-bef4-4cca-98cc-de92566c9cbc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>typeahead-on-select</name>
      <type>Main</type>
      <value>selectPerson($item, $index)</value>
      <webElementGuid>d552cc11-84db-4de6-8a51-a0e268a3387c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;relationship&quot;)/p[@class=&quot;left&quot;]/input[@class=&quot;person-typeahead ng-pristine ng-untouched ng-valid ng-empty&quot;]</value>
      <webElementGuid>7d30fa6a-b1ba-4575-a257-2921084f3af6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@type='text'])[15]</value>
      <webElementGuid>e8b30907-2d45-40e4-9f2a-2ceb876c13f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='relationship']/p[2]/input</value>
      <webElementGuid>c5ba5856-51c8-4a24-a159-aff1c0fb52d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/p[2]/input</value>
      <webElementGuid>865b6242-3471-452d-a0f6-0addd40e15cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = 'Person Name']</value>
      <webElementGuid>b5ecc8f5-abed-48da-9674-5bd3c16f3fc9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
