<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_concat(What, , s the patient phone nu_a898f7</name>
   <tag></tag>
   <elementGuidId>781455a9-a693-4ff8-af3d-24291b7244bb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#fr954-field</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name=&quot;phoneNumber&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2ab6a199-66c3-4f01-839c-91d809ef5030</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>d7f94b4d-286d-48a7-ba59-a3622278911a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>fr954-field</value>
      <webElementGuid>19269be0-1982-4afd-bfff-b4477c33abc9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>phoneNumber</value>
      <webElementGuid>953fe2da-2135-4013-ac2b-72d57e3709ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>phone focused</value>
      <webElementGuid>93946794-9f96-4a9f-920e-cad71cde7e4c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;fr954-field&quot;)</value>
      <webElementGuid>c96cf4fe-575d-48a5-a0a5-c7e2d4cc4df5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='fr954-field']</value>
      <webElementGuid>6461695a-a85f-49ec-b81f-919ad6164ce5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//fieldset[@id='phoneNumberLabel']/p/input</value>
      <webElementGuid>540dd3c3-82a8-4b85-a8ba-1a6ef73c5af5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//fieldset[2]/p/input</value>
      <webElementGuid>0f0c5e3f-a6c9-4f1b-9f15-7b6542ac21d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'fr954-field' and @name = 'phoneNumber']</value>
      <webElementGuid>0a1b73f8-ffeb-4b6b-b35e-4f790ad196aa</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
