<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_familyname</name>
   <tag></tag>
   <elementGuidId>8ebb7bf5-e39b-429e-a595-928f67e8dda2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[contains(@name,&quot;familyName&quot;)]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#fr3569-field</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>73850e2b-e1ff-4751-9fd4-c5787f6494e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>4d7175fc-d566-4915-927e-a763ac4f1c94</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>fr3569-field</value>
      <webElementGuid>51bcc9fe-10ce-407f-a5b5-f33d4956bdd4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>familyName</value>
      <webElementGuid>b3bc7fa5-e3ed-4d56-8c7b-f06a95e89d63</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>required ui-autocomplete-input focused</value>
      <webElementGuid>ba70e72c-17a6-4619-a364-6605b0ca5966</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>3246e491-c96f-4bf5-9c49-f8420279b931</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;fr3569-field&quot;)</value>
      <webElementGuid>01df465d-43f7-4994-bbae-64dc50863eef</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='fr3569-field']</value>
      <webElementGuid>93aa1e8b-2146-488a-992f-8f36f8aff50d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//fieldset[@id='demographics-name']/div/p[3]/input</value>
      <webElementGuid>1482715b-24ce-44f4-b8a9-386612fc7acc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p[3]/input</value>
      <webElementGuid>c761722f-3f77-4e9e-946c-3099d8f50bd2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'fr3569-field' and @name = 'familyName']</value>
      <webElementGuid>3c6baeac-b763-45e9-a150-e7a6ad2bfbf9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
