<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_CityVillage_cityVillage</name>
   <tag></tag>
   <elementGuidId>8e2021c2-ee6b-44d3-be8d-3010e1f89a5e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#cityVillage</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='cityVillage']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>22433654-180f-49a6-afb9-a3fcc36ac98a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>b68d57f3-1a29-4a23-bf6a-d7adc53f9abc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cityVillage</value>
      <webElementGuid>46568a00-aa76-4363-b77b-3282f85e0c12</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>cityVillage</value>
      <webElementGuid>ec081fbe-f9bc-46c6-8dd9-5f54e09a389d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>10</value>
      <webElementGuid>af475316-b91c-41a9-8e2a-99520b9770f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cityVillage&quot;)</value>
      <webElementGuid>993c6d01-fca4-461f-ad63-72e2c30c05e4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='cityVillage']</value>
      <webElementGuid>52c4a19a-ff47-4174-9776-2f6aaee125aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//fieldset[@id='null']/p[6]/input</value>
      <webElementGuid>dd117e49-d06a-43ef-8867-03f67e0ac678</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p[6]/input</value>
      <webElementGuid>87a0bd41-1a07-493b-b348-89032ba34c03</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'cityVillage' and @name = 'cityVillage']</value>
      <webElementGuid>4f4dd645-b8df-4774-8a04-4a050256114e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
