<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_(required)_birthdateYear-field</name>
   <tag></tag>
   <elementGuidId>b71583a8-a492-4439-9aa5-baea555f1d4d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#birthdateYear-field</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='birthdateYear-field']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0d9a2b57-9961-4573-87d2-085a143d9ae0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>2009dec5-14ab-4add-8208-b6fd98dfb4bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>birthdateYear-field</value>
      <webElementGuid>47cdf3f7-929e-48f2-bcb6-7ee838309848</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>birthdateYear</value>
      <webElementGuid>f04d7bf2-5c9e-4d1e-bd04-4e7d47059457</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>year number numeric-range date-component requiredTitle focused</value>
      <webElementGuid>d150eabb-ea6e-4b3b-8f36-a3f96bcaeedd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>2aaf8e3f-b107-4a2c-a96e-361d984adf99</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>4</value>
      <webElementGuid>a2b39936-3cae-48ef-8249-ed81d242023f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>min</name>
      <type>Main</type>
      <value>1905</value>
      <webElementGuid>97b84e20-6581-44e7-9d83-a1d87d40c2c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>max</name>
      <type>Main</type>
      <value>2025</value>
      <webElementGuid>4d61cb1b-ea2f-4653-9415-75c1be69d69f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;birthdateYear-field&quot;)</value>
      <webElementGuid>52e3caee-33c1-40b2-9e52-e2a608ed18dc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='birthdateYear-field']</value>
      <webElementGuid>dba356a9-c379-497f-84ea-4fd04f933be3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//fieldset[@id='demographics-birthdate']/p[4]/input</value>
      <webElementGuid>4170e45a-2099-4f49-96d9-7beb32cb8ef6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p[4]/input</value>
      <webElementGuid>b838e2ac-2635-45da-8913-e6f97b55ad6f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'birthdateYear-field' and @name = 'birthdateYear']</value>
      <webElementGuid>c96add16-4b6c-4674-b580-2ca37c941969</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
