<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_Password_togglePassword</name>
   <tag></tag>
   <elementGuidId>aaa0070c-9708-4d20-a90f-b9ba1de4fd51</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#togglePassword</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//i[@id='togglePassword']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>41c400f3-4725-4d4c-8669-4019d9ebfad3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fa fa-eye</value>
      <webElementGuid>2ac1e1a9-cea0-4828-8756-227900c0945d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>togglePassword</value>
      <webElementGuid>464894f7-fed8-44a4-9043-8665002d19eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;togglePassword&quot;)</value>
      <webElementGuid>af2a467e-d65f-4c60-a45b-ab0af8126d78</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//i[@id='togglePassword']</value>
      <webElementGuid>3de46c97-d42a-44c6-811d-2333143a3e7d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='login-form']/fieldset/p[2]/i</value>
      <webElementGuid>aec0896d-0324-4d52-9005-21fef543b93e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p[2]/i</value>
      <webElementGuid>fd58098e-3616-41b7-816b-a37d7b8c0e63</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//i[@id = 'togglePassword']</value>
      <webElementGuid>b7f1ab0a-2434-42ab-9104-dbf353f28977</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
