<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>confirm_name</name>
   <tag></tag>
   <elementGuidId>0e7ba7d8-670c-41f5-be38-78b41f78aa30</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#dataCanvas > div > p</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='dataCanvas']/div/p</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>7a7a8391-7b91-41b0-912f-3cd9ffcfdf44</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Name: Fawzi, Ridwan, F</value>
      <webElementGuid>d2bbeece-63d9-437f-b9aa-f0758738cc5e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dataCanvas&quot;)/div[1]/p[1]</value>
      <webElementGuid>4d122dbe-80b3-4ba0-b89b-2bb2c8c9250e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dataCanvas']/div/p</value>
      <webElementGuid>73f3c1e0-f505-4b64-89a8-cdb0677fa106</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Who is the patient related to?'])[1]/following::p[4]</value>
      <webElementGuid>8350f344-a661-4a4a-8cd1-9074a1973ab9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Relatives'])[2]/following::p[4]</value>
      <webElementGuid>810b763e-7af6-4586-8db4-0acaa45d5439</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Gender:'])[1]/preceding::p[1]</value>
      <webElementGuid>6e9de135-95cd-441c-acbd-71e7a7ac160e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Fawzi, Ridwan, F']/parent::*</value>
      <webElementGuid>bc988397-0a85-41bf-bd79-e62fb57cddbf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/p</value>
      <webElementGuid>461ccfb0-2d26-499b-b7c3-044d92a16197</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = 'Name: Fawzi, Ridwan, F' or . = 'Name: Fawzi, Ridwan, F')]</value>
      <webElementGuid>d0314a9d-3f9a-4ba3-84db-157d609bba88</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
