<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>confirm_gender</name>
   <tag></tag>
   <elementGuidId>e7515890-996f-468b-8ba3-5ec144f2a221</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#dataCanvas > div > p:nth-of-type(2)</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='dataCanvas']/div/p[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>ab3a436d-c7b7-49e7-a7cf-a8bcdf1551b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Gender: Male</value>
      <webElementGuid>da85b6d9-07c6-4b5e-82d4-5e83d68863c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dataCanvas&quot;)/div[1]/p[2]</value>
      <webElementGuid>0f2b11bb-01a3-4207-a89d-3bceebfd265d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dataCanvas']/div/p[2]</value>
      <webElementGuid>9d2c5eb1-3534-4d07-90cf-abf4471c3867</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Name:'])[1]/following::p[1]</value>
      <webElementGuid>bbfb74db-0b0c-451b-b50a-3590bd006aa4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Who is the patient related to?'])[1]/following::p[5]</value>
      <webElementGuid>fdd216f1-3f84-4e57-9808-e2690568f7fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Birthdate:'])[1]/preceding::p[1]</value>
      <webElementGuid>7627913a-4679-47c2-9cc9-f6ee3b0062a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/p[2]</value>
      <webElementGuid>2babc9c9-5da9-4b9f-a3c5-81cc887af716</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = 'Gender: Male' or . = 'Gender: Male')]</value>
      <webElementGuid>a4d84e25-c584-43bc-99ae-05ab25927dda</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
