<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>confirm_phone_number</name>
   <tag></tag>
   <elementGuidId>d8ea80eb-f8ea-4f3e-b792-7155b0de78a3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div > p:nth-of-type(5)</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='dataCanvas']/div/p[5]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>b72e0c63-95df-454d-a1a6-9f36792d6635</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Phone Number: 0822165581287</value>
      <webElementGuid>b2892156-d5b4-4a6d-b40a-cfc5dd61873b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dataCanvas&quot;)/div[1]/p[5]</value>
      <webElementGuid>1ebf27fb-5c33-4a30-872b-29533e56956e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dataCanvas']/div/p[5]</value>
      <webElementGuid>bc0c30cd-4354-4b7c-9e43-20596d714e6f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Address:'])[1]/following::p[1]</value>
      <webElementGuid>03e3d391-312f-41a8-918f-9adc91dfb2ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Birthdate:'])[1]/following::p[2]</value>
      <webElementGuid>12025a69-25f9-42fb-bb00-895e681392cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Relatives:'])[1]/preceding::p[1]</value>
      <webElementGuid>b391e518-bb2a-49d3-83db-4f9fbc57ee9b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='0822165581287']/parent::*</value>
      <webElementGuid>5fabe02f-5b28-49a7-9bc1-3d9c8271c2ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/p[5]</value>
      <webElementGuid>fd5dedda-7a98-4cb9-bdbf-c4f9f982d58f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = 'Phone Number: 0822165581287' or . = 'Phone Number: 0822165581287')]</value>
      <webElementGuid>b14bf195-ad01-4c9b-892b-dfc62dca72c0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
